#!/usr/bin/env zsh

if (( ${+commands[nvim]} )); then
    export EDITOR=nvim
elif (( ${+commands[emacs]} )); then
    export EDITOR='$emacsclient -c -a ""'
else
    export EDITOR=vim
fi

eval $EDITOR '$@'
