source ~/.vim/plugins.vim " include plugs"

if !has('nvim')
  set ttymouse=xterm2
endif

inoremap jk <ESC>
set mouse=a

" WSL yank support
let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path according to your mount point
if executable(s:clip)
	augroup WSLYank
		autocmd!
		autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
	augroup END
endif
